### ISSUE TITLE
Space appears between send message box and keyboard if used with a navigationGroup

### ISSUE THREAD

**Issue by bentindall** [pec1985/TiSMSView#32]
When using the smsview on a window within a navigationGroup, and you try to send a message, there is a large space between the send message bar and the keyboard. It seems to work fine if you use the window in "modal" mode.

**Comment by pec1985** [comment]
The only time I've seen this is when it is used in a tab group. The only way to "fix" it is to create the window with the tabBarHidden = true property.

**Comment by sindresorhus** [comment]
It can't be the only way to fix it?

I just noticed this problem using the SMSView in a tabGroup window.

It makes the SMSView unusable in any app that uses tabGroups...

![smsview tabgroup](https://img.skitch.com/20111010-bscm8uxe48kbt5xdx6dk5dij2m.png)

**Comment by pec1985** [comment]
Three options here:
1. If you think this is unusable, then don't use it.
2. Hide the tab bar
3. Fork it, fix it, and push it.

As of right now, I have not found a way to make it work with the tab bar on.

**Comment by sindresorhus** [comment]
1. I don't use a tabGroup in my current app, so not a problem for me right now, but I can see it as a big problem for someone else that need to use it with a tabGroup.
2. Not really an option for most devs, since they probably need the tabBar to navigate the app.
3. Wish I knew Objective-C.

I understand, no problem. Hope someone will fix this. So keep this issue open.

**Comment by pec1985** [comment]
Use the boolean: hasTab and it will fix the problem.

Ti.SMSView.createView({ hasTab: true });
